apiVersion: v1
kind: Namespace
metadata:
  name: flights
---
apiVersion: v1
kind: Service
metadata:
  name: flights
  namespace: flights
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: flights 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights 
  namespace: flights
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flights 
  template:
    metadata:
      labels:
        app: flights 
    spec:
      containers:
      - name: flights 
        image: asiregistry.azurecr.io/flights
        ports:
        - containerPort: 3000
        env:
        - name: "DB_HOST"
          value: "asi-db-server.mysql.database.azure.com"
        - name: "DB_NAME"
          value: "asi"
        - name: "DB_PORT"
          value: "3306"
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store01-inline
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "asi-kv2"
