apiVersion: v1
kind: Namespace
metadata:
  name: players
---
apiVersion: v1
kind: Service
metadata:
  name: players
  namespace: players
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 4000
  selector:
    app: players
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: players
  namespace: players
spec:
  replicas: 3
  selector:
    matchLabels:
      app: players
  template:
    metadata:
      labels:
        app: players
    spec:
      containers:
      - name: players
        image: asiregistry.azurecr.io/players
        ports:
        - containerPort: 4000
