apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: asi-kv2
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "86aa7778-9f61-4ffa-847b-a828de7bbb0a"
    keyvaultName: "asi-kv2"
    objects: |
      array:
        - |
          objectName: ASI-DB-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: ASI-DB-PASS
          objectType: secret
          objectVersion: ""
    tenantId: "b3ba8455-b951-4b0e-a726-dbbe66a57291"
