apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: asi-kv2
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "05825c63-7e73-4ba8-9b49-8ec2588f727c"
    keyvaultName: "asi-kv2"
    objects: |
      array:
        - |
          objectName: ASI-DB-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: ASI-DB-PASS
          objectType: secret
          objectVersion: ""
    tenantId: ${TENANT_ID}
