apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: asi-kv2
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "caf5bb24-391d-4c23-bc77-d5da35855de8"
    keyvaultName: "asi-kv2"
    objects: |
      array:
        - |
          objectName: ASI-DB-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: ASI-DB-PASS
          objectType: secret
          objectVersion: ""
    tenantId: ""
