apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: asi-kv2
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "41b4ea62-8ba3-4b4a-8f6c-4a5065a5a2d6"
    keyvaultName: "asi-kv2"
    objects: |
      array:
        - |
          objectName: ASI-DB-USER
          objectType: secret
          objectVersion: ""
        - |
          objectName: ASI-DB-PASS
          objectType: secret
          objectVersion: ""
    tenantId: "b3ba8455-b951-4b0e-a726-dbbe66a57291"
